//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewEggDeals.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewEggDeals.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;rss version=&quot;2.0&quot;&gt;
        ///&lt;channel&gt;
        ///&lt;title&gt;Newegg.com RSS Feed - Daily Deals&lt;/title&gt;
        ///&lt;link&gt;
        ///http://www.newegg.com/Product/ProductList.aspx?Submit=DailyDeals&amp;nm_mc=OTC-RSS&amp;cm_sp=OTC-RSS
        ///&lt;/link&gt;
        ///&lt;description&gt;
        ///Official Newegg.com RSS Feed - An up-to-date headlines on our latest sales, deals, and promotions. Subscribe now and never miss a single Newegg.com deal.
        ///&lt;/description&gt;
        ///&lt;language&gt;en-us&lt;/language&gt;
        ///&lt;lastBuildDate&gt;Tue, 17 Feb 2015 10:21:01GMT&lt;/lastBuildDate&gt;
        ///&lt;ttl&gt;15&lt;/ttl&gt;
        ///&lt;image&gt;
        ///&lt;title&gt;Newegg.com&lt;/t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FullXml {
            get {
                return ResourceManager.GetString("FullXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;item&gt;
        ///&lt;title&gt;
        ///$259.99 - ASUS Transformer Book T100TAF-B1-BF Intel Atom Z3735F (1.33GHz) 2GB Memory 32GB SSD 10.1&quot; Touchscreen 2-in-1 Tablet Windows 8.1 32-Bit
        ///&lt;/title&gt;
        ///&lt;link&gt;
        ///http://www.newegg.com/Product/Product.aspx?Item=N82E16834232207&amp;nm_mc=OTC-RSS&amp;cm_sp=OTC-RSS-_-All%20Ultrabooks-_-ASUS-_-N82E16834232207
        ///&lt;/link&gt;
        ///&lt;description&gt;
        ///&lt;div style=&quot;width:125px;float:left;clear:none;border:1px solid #ccc;background-color:#fff;padding:15px 5px;margin:10px 10px 10px 0px;&quot;&gt;         /// &lt;img border=&quot;0&quot; src=&quot;http://imag [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleXml {
            get {
                return ResourceManager.GetString("SampleXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Solution {
            get {
                object obj = ResourceManager.GetObject("Solution", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
